// Autogenerated from Pigeon (v16.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class SPConfig (
  val accountId: Long,
  val propertyId: Long,
  val propertyName: String,
  val pmId: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): SPConfig {
      val accountId = list[0].let { if (it is Int) it.toLong() else it as Long }
      val propertyId = list[1].let { if (it is Int) it.toLong() else it as Long }
      val propertyName = list[2] as String
      val pmId = list[3] as String
      return SPConfig(accountId, propertyId, propertyName, pmId)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      accountId,
      propertyId,
      propertyName,
      pmId,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object SourcepointUnifiedCmpApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SPConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SPConfig -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SourcepointUnifiedCmpApi {
  fun loadPrivacyManager(accountId: Long, propertyId: Long, propertyName: String, pmId: String, callback: (Result<Unit>) -> Unit)
  fun showPrivacyManager(config: SPConfig, callback: (Result<Unit>) -> Unit)
  fun setPlatformCmpConfig(config: SPConfig, callback: (Result<Unit>) -> Unit)
  fun init(accountId: Long, propertyId: Long, propertyName: String, pmId: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by SourcepointUnifiedCmpApi. */
    val codec: MessageCodec<Any?> by lazy {
      SourcepointUnifiedCmpApiCodec
    }
    /** Sets up an instance of `SourcepointUnifiedCmpApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: SourcepointUnifiedCmpApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sourcepoint_unified_cmp_android.SourcepointUnifiedCmpApi.loadPrivacyManager", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val propertyIdArg = args[1].let { if (it is Int) it.toLong() else it as Long }
            val propertyNameArg = args[2] as String
            val pmIdArg = args[3] as String
            api.loadPrivacyManager(accountIdArg, propertyIdArg, propertyNameArg, pmIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sourcepoint_unified_cmp_android.SourcepointUnifiedCmpApi.showPrivacyManager", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as SPConfig
            api.showPrivacyManager(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sourcepoint_unified_cmp_android.SourcepointUnifiedCmpApi.setPlatformCmpConfig", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as SPConfig
            api.setPlatformCmpConfig(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sourcepoint_unified_cmp_android.SourcepointUnifiedCmpApi.init", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val propertyIdArg = args[1].let { if (it is Int) it.toLong() else it as Long }
            val propertyNameArg = args[2] as String
            val pmIdArg = args[3] as String
            api.init(accountIdArg, propertyIdArg, propertyNameArg, pmIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
