name: sourcepoint_unified_cmp_flutter_webview_extension
description: Flutter webview extension to preload the sourcepoint unified CMP consent
version: 0.1.22
homepage: https://github.com/thekorn/sourcepoint_unified_cmp
repository: https://github.com/thekorn/sourcepoint_unified_cmp/tree/main/packages/sourcepoint_unified_cmp_flutter_webview_extension 


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  sourcepoint_unified_cmp: ^0.1.22
  webview_flutter: ^4.7.0

dev_dependencies: 
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  very_good_analysis: ^6.0.0
