name: sourcepoint_unified_cmp_flutter_inappwebview_extension
description: Flutter webview extension to preload the sourcepoint unified CMP consent
version: 0.1.26
homepage: https://github.com/thekorn/sourcepoint_unified_cmp
repository: https://github.com/thekorn/sourcepoint_unified_cmp/tree/main/packages/sourcepoint_unified_cmp_flutter_inappwebview_extension 


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  sourcepoint_unified_cmp: ^0.1.26

dev_dependencies:
  build_runner: ^2.4.8
  flutter_inappwebview_platform_interface: ^1.0.10
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  very_good_analysis: ^7.0.0
