name: sourcepoint_unified_cmp_flutter_inappwebview_extension
description: Flutter webview extension to preload the sourcepoint unified CMP consent
version: 0.1.21
homepage: https://github.com/thekorn/sourcepoint_unified_cmp
repository: https://github.com/thekorn/sourcepoint_unified_cmp/tree/main/packages/sourcepoint_unified_cmp_flutter_inappwebview_extension 


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  sourcepoint_unified_cmp_platform_interface: ^0.1.21

dev_dependencies: 
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  very_good_analysis: ^6.0.0
