name: sourcepoint_unified_cmp_flutter_webview_extension

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/sourcepoint_unified_cmp_flutter_webview_extension.yaml"
      - "packages/sourcepoint_unified_cmp_flutter_webview_extension/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/sourcepoint_unified_cmp_flutter_webview_extension.yaml"
      - "packages/sourcepoint_unified_cmp_flutter_webview_extension/**"

jobs:
  fvmrc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: get fvmrc
        id: fvmrc
        uses: ActionsTools/read-json-action@v1.0.5
        with:
          file_path: ".fvmrc"
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    needs: fvmrc
    with:
      setup: |
        echo "Setup Melos..."
        dart pub global activate melos
        echo "Setup Melos... Done"
        echo "removing fvm from melos.yaml"
        sed -i 's/^\(  sdkPath:.*\)$/# \1/' ../../pubspec.yaml
        echo "removing fvm from melos.yaml... Done"
        echo "bootstraping packages..."
        melos bootstrap
        echo "bootstraping packages... Done"
      flutter_channel: stable
      flutter_version: ${{needs.fvmrc.outputs.flutter}}
      working_directory: packages/sourcepoint_unified_cmp_flutter_webview_extension
      min_coverage: 80

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      min_score: 120
